name: Cherry pick commit(s)

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to cherrypick'
        required: true
      tag:
        description: 'Branch to cherry pick to'
        required: true
        default: 'v5-09-XX'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Decide which branch to use
      run: |
        cat << EOF >> "$GITHUB_OUTPUT"
        branch=$(echo AliPhysics-${{ github.event.inputs.tag }}-01-patches | sed -e's/[a-z][a-z]*-01-patches$/-01-patches/')
        EOF
      id: decide_release_branch
    - uses: actions/checkout@v5
      with:
        ref: "${{ steps.decide_release_branch.outputs.branch }}"
    - name: Update the branch
      run: |
        git config --global user.email "alibuild@cern.ch"
        git config --global user.name "ALICE Action Bot"
        git checkout ${{ steps.decide_release_branch.outputs.branch }}
        git fetch --all
        git cherry-pick ${{ github.event.inputs.commit }}
        git push
