---
name: Clean PR checks

'on':
  workflow_dispatch:
    inputs:
      pr:
        description: PR number in this repo to be cleaned
        type: string   # can't use number here
        required: true

      # Warning: GitHub limits the total number of inputs to 10, so a maximum of
      # 9 checks is allowed here!
      # Warning: the check_* keys are magic and must consist of the string
      # "check_" followed by the applicable check name exactly. The
      # "description" field is only the human-readable label for the input.
      'check_build/AliGenerators/generators':
        description: build/AliGenerators/generators
        type: boolean
        default: true
      'check_build/AliRoot/alidist':
        description: build/AliRoot/alidist
        type: boolean
        default: true
      'check_build/O2/alidist':
        description: build/O2/alidist
        type: boolean
        default: true
      'check_build/O2/alidist-cs8':
        description: build/O2/alidist-cs8
        type: boolean
        default: true
      'check_build/O2/alidist-dataflow-cs8':
        description: build/O2/alidist-dataflow-cs8
        type: boolean
        default: true
      'check_build/O2/alidist-slc9-aarch64':
        description: build/O2/alidist-slc9-aarch64
        type: boolean
        default: true
      'check_build/O2/alidist-slc9-x86':
        description: build/O2/alidist-slc9-x86
        type: boolean
        default: true
      'check_build/O2/alidist-ubuntu2204':
        description: build/O2/alidist-ubuntu2204
        type: boolean
        default: true
      'check_build/O2/fullCI/alidist':
        description: build/O2/fullCI/alidist
        type: boolean
        default: true

permissions: {}

jobs:
  clean:
    name: Clean PR checks
    uses: alisw/ali-bot/.github/workflows/clean-pr-checks.yml@master
    with:
      owner: ${{ github.event.repository.owner.login }}
      repo: ${{ github.event.repository.name }}
      pr: ${{ github.event.inputs.pr }}
      checks: ${{ toJSON(github.event.inputs) }}
    permissions:
      pull-requests: read  # to get last commit for pr (octokit/graphql-action)
      statuses: write      # for set-github-status
