name: Prepare O2 tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to prepare'
        required: true
        default: 'vX.Y.Z'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Decide which branch to use
      run: |
        cat << EOF
        ::set-output name=branch::$(echo O2-${{ github.event.inputs.tag }}-patches | tr . - | sed -e's/\.[0-9]*-patches$/-patches/')
        EOF
      id: decide_release_branch
    - uses: actions/checkout@v2
      with:
        ref: "master"
    - name: Update the branch
      run: |
        python3 -m venv alibot
        source alibot/bin/activate
        python3 -m pip install setuptools==49.6.0 wheel
        python3 -m pip install git+https://github.com/alisw/ali-bot@master
        git checkout -B ${{ steps.decide_release_branch.outputs.branch }}
        DEFAULTS=o2 OVERRIDE_TAGS="O2=${{ github.event.inputs.tag }}" OVERRIDE_VERSIONS="O2=${{ github.event.inputs.tag }}" alidist-override-tags
        DEFAULTS=o2-dataflow OVERRIDE_TAGS="O2=${{ github.event.inputs.tag }}" OVERRIDE_VERSIONS="O2=${{ github.event.inputs.tag }}" alidist-override-tags
        git config --global user.email "alibuild@cern.ch"
        git config --global user.name "ALICE Action Bot"
        git commit -m "Bump to ${{ github.event.inputs.tag }}" -a || echo "No changes to commit"
        git show
    #    git push
    #    git tag O2-${{ github.event.inputs.tag }}
    #    git push origin O2-${{ github.event.inputs.tag }}
    #- name: Create Release
    #  id: create_release
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #  with:
    #    tag_name: O2-${{ github.event.inputs.tag }}
    #    release_name: O2-${{ github.event.inputs.tag }}
    #    draft: false
    #    prerelease: false

